// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemQH_U0kTLstiZm1srhHd1pJEcNKE9JY',
    appId: '1:683254278147:web:584e2ed10ec88ddf89c636',
    messagingSenderId: '683254278147',
    projectId: 'wilsonapitask',
    authDomain: 'wilsonapitask.firebaseapp.com',
    storageBucket: 'wilsonapitask.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9JElX8alNDP75vrnn_qPeEppzbFGQy80',
    appId: '1:683254278147:android:dbf269b082ff733189c636',
    messagingSenderId: '683254278147',
    projectId: 'wilsonapitask',
    storageBucket: 'wilsonapitask.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaeNPNBr7Tbndabg_wg5NXewxngr8UDr4',
    appId: '1:683254278147:ios:74210fc609c168c589c636',
    messagingSenderId: '683254278147',
    projectId: 'wilsonapitask',
    storageBucket: 'wilsonapitask.appspot.com',
    iosClientId: '683254278147-sdf2tlh4dqv0qdjadm8t6j5f5o29o7am.apps.googleusercontent.com',
    iosBundleId: 'com.example.wilsonApiTask',
  );
}
